print("-------------  ")
print("|           |  ")
print("|              ")
print("|              ")
print("|              ")
print("|              ")
print("|              ")
print("|")

print("-------------  ")
print("|           |  ")
print("|         (º-º)")
print("|              ")
print("|              ")
print("|              ")
print("|              ")
print("|")

print("-------------  ")
print("|           |  ")
print("|         (º-º)")
print("|           |  ")
print("|              ")
print("|              ")
print("|              ")
print("|")

print("-------------  ")
print("|           |  ")
print("|         (º-º)")
print("|          /|  ")
print("|              ")
print("|              ")
print("|              ")
print("|")

print("-------------  ")
print("|           |  ")
print("|         (º-º)")
print("|          /|\ ")
print("|              ")
print("|              ")
print("|              ")
print("|")

print("-------------  ")
print("|           |  ")
print("|         (º-º)")
print("|          /|\ ")
print("|          /   ")
print("|              ")
print("|              ")
print("|")

print("Você Perdeu... (º_º)")
print("-------------       ")
print("|           |       ")
print("|         (x_x)     ")
print("|          /|\      ")
print("|          / \\     ")
print("|                   ")
print("|                   ")
print("|")
